b_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="/to_do/", permanent=False)),
    path("to_do/", include("to_do.urls")),
    path('__debug__/', include("debug_toolbar.urls")),
]

to_do/urls.py
from django.urls import path


from . import views



app_name = "to_do"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("add_task/", views.add_task, name="add_task"),
    path("add_sub_task/<int:task_id>/", views.add_subtask, name="add_subtask"),
    path("complete_task/<int:task_id>/", views.complete_task, name="complete_task"),
    path("delete_task/<int:task_id>/", views.delete_task, name="delete_task"),
    path("completed/", views.completed_tasks, name="completed_tasks"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('to_do/', include('to_do.urls')),
]

to_do/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_description = models.CharField(max_length=200)
    date_added = models.DateTimeField("date added")
    parent_task = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name="subtask")
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.task_description

to_do/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class CustomRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields= ('username', 'password1', 'password2')


class CustomLoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    class Meta:
        model = User
        fields = ('username', 'password')

to_do/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse

from .forms import CustomRegistrationForm, CustomLoginForm

from .models import Task


class CustomLoginView(LoginView):
    template_name = 'registration/login.html'

    def get(self, request, *args, **kwargs):
        # Render the login form and registration form on GET request
        login_form = AuthenticationForm()
        registration_form = UserCreationForm()
        return self.render_to_response(
            self.get_context_data(
                login_form=login_form,
                registration_form=registration_form,
                error_message=None
            )
        )

    def post(self, request, *args, **kwargs):
        error_message = None

        # Process the login form or registration form on POST request
        if 'login_submit' in request.POST:
            # Handle login submission
            login_form = AuthenticationForm(data=request.POST)
            if login_form.is_valid():
                print("login form is valid")
                from django.contrib.auth import login
                user = login_form.get_user()
                login(request, user)
                return redirect('to_do:index')  # Redirect to the home page after successful login
            else:
                # Handle login form errors
                print("login form is not valid")
                error_message = "Login failed. Please check your credentials."

        elif 'registration_submit' in request.POST:
            # Handle registration form submission
            registration_form = UserCreationForm(data=request.POST)
            if registration_form.is_valid():
                user = registration_form.save()  # Save the new user
                from django.contrib.auth import login
                login(request, user)  # Log in the newly registered user
                return redirect('to_do:index')  # Redirect to the home page after successful registration
            else:
                # Handle registration form errors
                error_message = "Registration failed. Please check your information."

        # If there was an error in either login or registration, render the form with an error message
        print("We got here")
        return self.render_to_response(
            self.get_context_data(
                login_form=AuthenticationForm(),
                registration_form=UserCreationForm(),
                error_message=error_message
            )
        )

@login_required
def index(request):
    # Call the common function to handle form submission
    handle_form_submission(request, 'to_do:index')

    if request.method == 'POST':
        # Check if the "complete" or "delete" form was submitted
        if 'complete' in request.POST:
            task_id = request.POST['complete']
            complete_task(request, task_id)
        elif 'delete' in request.POST:
            task_id = request.POST['delete']
            delete_task(request, task_id)

        # Retrieve all tasks, including completed tasks, for display
    all_root_tasks = Task.objects.filter(user=request.user, completed=False, parent_task__isnull=True).prefetch_related("subtask")

    return render(request,
                  'to_do/index.html',
                  {'all_root_tasks': all_root_tasks
                   })

@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)

    # Toggle the completion status
    task.completed = not task.completed
    task.save()

    # If root task marked complete all subtasks updated to complete
    if not task.parent_task and task.completed:
        subtasks = Task.objects.filter(parent_task=task)
        subtasks.update(completed=True)

    return HttpResponse(status=204)  # 204 No Content response


@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    task.delete()
    return redirect('to_do:index')

def handle_form_submission(request, redirect_url, parent_task=None):
    # Handle create task form submissions

    if request.method == 'POST':
        # Determine whether it's a new task or a subtask form based on the input name
        form_prefix = f'subtask_{parent_task.id}' if parent_task else 'new_task'

        # Get the task description from the form input
        task_description = request.POST.get(form_prefix)

        # Create a new Task object and save it to the database
        Task.objects.create(user=request.user, task_description=task_description, date_added=timezone.now(), parent_task=parent_task)

        # Redirect to the specified URL
        return redirect(redirect_url)

def add_task(request):
    # Call the common function to handle form submission
    handle_form_submission(request, 'to_do:index')

    return redirect("to_do:index")

def add_subtask(request, task_id):
    try:
        parent_task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        parent_task = None

    if parent_task:
            handle_form_submission(request, "to_do:index", parent_task=parent_task)

    return redirect("to_do:index")

@login_required
def completed_tasks(request):
    # Retrieve all completed tasks for the user
    completed_tasks = Task.objects.filter(user=request.user, completed=True).prefetch_related("subtask")

    return render(request, 'to_do/completed.html', {'completed_tasks': completed_tasks})

class CustomLogoutView(LogoutView):
    next_page = 'to_do:login'

to_do/templates/to_do/completed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Completed Tasks</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

</head>
<body>
    <h1>Completed Tasks</h1>

    <a href="{% url 'to_do:index' %}">See Your Pending Tasks</a>

    {% if completed_tasks %}
        <ul>
            {% for task in completed_tasks %}
                <li>
                    {{ task.task_description }}

                    <!-- Form for marking task as incomplete -->
                    <form method="post" action="{% url 'to_do:complete_task' task.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="completed" value="false">
                        <button type="submit" name="complete">Mark as Incomplete</button>
                    </form>

                    <!-- Form for deleting task -->
                    <form method="post" action="{% url 'to_do:delete_task' task.id %}">
                        {% csrf_token %}
                        <button type="submit" name="delete">Delete</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No completed tasks are available.</p>
    {% endif %}

<a href="{% url 'to_do:logout' %}">Logout</a>

<script src="{% static 'complete_button.js' %}"></script>

</body>
</html>

to_do/templates/to_do/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>2DO</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

</head>
<body>

<a href="{% url 'to_do:completed_tasks' %}">See Your Completed Tasks</a>

{% if all_root_tasks %}
    <ul>
    {% for task in all_root_tasks %}
        <li>
            <div class="task-container">
                <span class="task-description">{{ task.task_description }}</span>

                <!-- Form for marking task as complete -->
                <form method="post" action="{% url 'to_do:complete_task' task.id %}">
                    {% csrf_token %}
                    <button type="submit" name="complete">Mark as Complete</button>
                </form>

                <!-- Form for deleting task -->
                <form method="post" action="{% url 'to_do:delete_task' task.id %}">
                    {% csrf_token %}
                    <button type="submit" name="delete">Delete</button>
                </form>

                <!-- Add a form for adding subtasks for each task -->
                <form method="post" action="{% url 'to_do:add_subtask' task.id %}">
                    {% csrf_token %}
                    <label for="subtask_{{ task.id }}">Subtask:</label>
                    <input type="text" id="subtask_{{ task.id }}" name="subtask_{{ task.id }}" required>
                    <button type="submit">Add</button>
                </form>
            </div>

            {% if task.subtask.all %}
                <ul>
                    {% for subtask in task.subtask.all %}
                        <li>
                            <div class="task-container">
                                <span class="task-description">{{ subtask.task_description }}</span>

                                <!-- Form for marking subtask as complete -->
                                <form method="post" action="{% url 'to_do:complete_task' subtask.id %}">
                                    {% csrf_token %}
                                    <button type="submit" name="complete">Mark as Complete</button>
                                </form>

                                <!-- Form for deleting subtask -->
                                <form method="post" action="{% url 'to_do:delete_task' subtask.id %}">
                                    {% csrf_token %}
                                    <button type="submit" name="delete">Delete</button>
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No task is available.</p>
{% endif %}

<form method="post" action="{% url 'to_do:add_task' %}">
    {% csrf_token %}
    <label for="new_task">New Task:</label>
    <input type="text" id="new_task" name="new_task" required>
    <button type="submit">Add Task</button>
</form>

<form method="post" action="{% url 'to_do:logout' %}">
    {% csrf_token %}
    <input type="submit" value="Logout">
  </form>

<script src="{% static 'complete_button.js' %}"></script>

</body>


</html>